# Installs Kofax RPA 11.3.0.1 from https://hub.docker.com/u/kofax
# a Management Console, a RoboServer, a Synchronizer, a Robot Filesystem and Kapplets
# The RoboServer count can be scaled.
#
version: '2.1'
networks:
  net:
services:
  postgres-service:
    image: postgres:10
    environment:
      - POSTGRES_USER=scheduler
      - POSTGRES_PASSWORD=schedulerpassword
      - POSTGRES_DB=scheduler
    networks:
      - net
  managementconsole-service:
    image: kofax/rpa-managementconsole:11.4.0.0.197
    depends_on:
      - postgres-service
    ports:
      - 83:8080
    environment:
      - CONTEXT_RESOURCE_VALIDATIONQUERY=SELECT 1
      - CONTEXT_RESOURCE_USERNAME=scheduler
      - CONTEXT_RESOURCE_PASSWORD=schedulerpassword
      - CONTEXT_RESOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - CONTEXT_RESOURCE_URL=jdbc:postgresql://postgres-service:5432/scheduler
      - CONTEXT_CHECK_DATABASE_TIMEOUT=600
      # enter your license here, or type it through the GUI in first login
      - CONFIG_LICENSE_NAME=
      - CONFIG_LICENSE_EMAIL=
      - CONFIG_LICENSE_COMPANY=${LICENSE_COMPANY}
      - CONFIG_LICENSE_PRODUCTIONKEY=
      - CONFIG_LICENSE_NONPRODUCTIONKEY=${LICENSE_NONPRODUCTIONKEY}
    networks:
      - net
  roboserver-service:
    image: kofax/rpa-roboserver:11.4.0.0.197
    depends_on:
      - managementconsole-service
      - postgres-service
    networks:
      - net
    environment:
      - ROBOSERVER_ENABLE_MC_REGISTRATION=true
      - ROBOSERVER_MC_URL=http://managementconsole-service:8080/
      - ROBOSERVER_MC_CLUSTER=Non Production
      - ROBOSERVER_MC_USERNAME=admin
      - ROBOSERVER_MC_PASSWORD=admin
      - ROBOSERVER_ENABLE_SOCKET_SERVICE=true
      - ROBOSERVER_SERVER_NAME=roboserver
      - WRAPPER_MAX_MEMORY=2048
  synchronizer-service:
    image: kofax/rpa-synchronizer:11.4.0.0.197
    depends_on:
      - managementconsole-service
    networks:
      - net
    environment:
      - SYNCHRONIZER_MC_URL=http://managementconsole-service:8080/
      - SYNCHRONIZER_USERNAME=admin
      - SYNCHRONIZER_PASSWORD=admin
      - SYNCHRONIZER_INTERVAL=3
  robotfilesystem-service:
    image: kofax/rpa-robotfilesystem:11.4.0.0.197
    depends_on:
      - managementconsole-service
    ports:
      - 81:8080
    networks:
      - net
    environment:
      - RFS_MC_URL=http://managementconsole-service:8080/
      - RFS_MC_USERNAME=admin
      - RFS_MC_PASSWORD=admin
      - RFS_DATA_PATH=C:/data
      - RFS_CREATE_FOLDERS=true
      - RFS_ALLOW_ABSOLUTE_PATHS=true
  kapplets-service:
    image: kofax/rpa-kapplets:11.4.0.0.197
    depends_on:
      - managementconsole-service
    ports:
      - 84:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://kapplets-database-service:5432/kapplets
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=kapplets
      - SPRING_DATASOURCE_PASSWORD=kappletspassword
#      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.SQLServer2012Dialect
      - KAPPLETS_SERVICES_MC_CONNECTION_URL=http://managementconsole-service:8080/
      - KAPPLETS_SERVICES_MC_CONNECTION_USERNAME=admin
      - KAPPLETS_SERVICES_MC_CONNECTION_PASSWORD=admin
      - SLEEP_DELAY=30s
      - KAPPLETS_SERVICES_MC_CONNECTION_OAUTH_KAPPLETSBASEURL=
      - KAPPLETS_SERVICES_MC_CONNECTION_OAUTH_MCBASEURL=
      - KAPPLETS_SERVICES_MC_CONNECTION_OAUTH_CLIENTSECRET=
    networks:
      - net
  kapplets-database-service:
    image: postgres:10
    environment:
      - POSTGRES_USER=kapplets
      - POSTGRES_PASSWORD=kappletspassword
      - POSTGRES_DB=kapplets
    networks:
      - net

