#
# An example docker-compose file featuring a kapplets server.
# It deploys a PostgreSQL instance, a Management Console, a RoboServer and a Kapplets instance.
#
# run (or update existing containers) with 
# docker compose -p rpa11-5-1 -f docker-compose-kapplets.yml up -d
# -p projectname
# -f filename
# -d detach (ie go back to commandline after success)

version: '3.8'
networks:
  net:


services:
  postgres-mcconfig-service:
    image: postgres:10
    environment:
      - POSTGRES_USER=scheduler
      - POSTGRES_PASSWORD=schedulerpassword
      - POSTGRES_DB=scheduler
    networks:
      - net
    ports:
      - 5433:5432
  postgres-kapplets-service:
    image: postgres:10
    environment:
      - POSTGRES_USER=kapplets
      - POSTGRES_PASSWORD=kapplets
      - POSTGRES_DB=kapplets
    networks:
      - net
  managementconsole-service:
    build:
      context: .
      dockerfile: docker/managementconsole/Dockerfile
    image: managementconsole:${Version:-11.5.0.1.0.324}
    depends_on:
      - postgres-mcconfig-service
    ports:
      - 87:8080
    environment:
      - LOGIN_CREATE_ADMIN_USER=true
      - LOGIN_INITIAL_ADMIN_USER=${ADMIN_USERNAME}
      - LOGIN_INITIAL_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - CONTEXT_RESOURCE_VALIDATIONQUERY=SELECT 1
      - CONTEXT_RESOURCE_USERNAME=scheduler
      - CONTEXT_RESOURCE_PASSWORD=schedulerpassword
      - CONTEXT_RESOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - CONTEXT_RESOURCE_URL=jdbc:postgresql://postgres-mcconfig-service:5432/scheduler
      # Create a Non Production Cluster
      - SETTINGS_CLUSTER_COUNT=1
      - SETTINGS_CLUSTER_NAME_1=Non Production
      - SETTINGS_CLUSTER_PRODUCTION_1=false
      - SETTINGS_CLUSTER_CONNECTION_TYPE_1=AS_SERVICE
      - SETTINGS_CLUSTER_DYNAMIC_LICENSE_1=true
      #      - CONFIG_SECURITY_JDBCDRIVERUPLOAD=ANY_HOST
      # installs JDBC drivers into /usr/local/tomcat/lib/jdbc
      - JDBC_DRIVER_URL_1=https://repo1.maven.org/maven2/mysql/mysql-connector-java/5.1.45/mysql-connector-java-5.1.45.jar
      - JDBC_DRIVER_URL_2=https://github.com/microsoft/mssql-jdbc/releases/download/v12.4.2/mssql-jdbc-12.4.2.jre8.jar
      # 0=automatic
      - SETTINGS_CLUSTER_LICENSEUNITS_1=0
      # roboserver log database
      - SETTINGS_ENTRY_COUNT=6
      - SETTINGS_ENTRY_KEY_1=USE_LOGDB
      - SETTINGS_ENTRY_VALUE_1=true
      - SETTINGS_ENTRY_KEY_2=LOGDB_SCHEMA
      - SETTINGS_ENTRY_VALUE_2=logdb
      - SETTINGS_ENTRY_KEY_3=LOGDB_HOST
      - SETTINGS_ENTRY_VALUE_3=postgres-robotlogs-service:5432
      - SETTINGS_ENTRY_KEY_4=LOGDB_TYPE
      - SETTINGS_ENTRY_VALUE_4=PostgreSQL
      - SETTINGS_ENTRY_KEY_5=LOGDB_USERNAME
      - SETTINGS_ENTRY_VALUE_5=logdb
      - SETTINGS_ENTRY_KEY_6=LOGDB_PASSWORD
      - SETTINGS_ENTRY_VALUE_6=logdbpassword
      # enter your license here, or type it through the GUI in first login
      - CONFIG_LICENSE_NAME=
      - CONFIG_LICENSE_EMAIL=
      - CONFIG_LICENSE_COMPANY=${LICENSE_COMPANY}
      - CONFIG_LICENSE_PRODUCTIONKEY=${LICENSE_PRODUCTIONKEY}
      - CONFIG_LICENSE_NONPRODUCTIONKEY=${LICENSE_NONPRODUCTIONKEY}
      # change to use your own, match with the Roboserver setting ROBOSERVER_MC_SHARED_SECRET
      - SERVICE_AUTHENTICATION_ROBOSERVER_SHARED_SECRET=${ROBOSERVER_SHAREDSECRET}
      - SERVICE_AUTHENTICATION_KAPPLETS_SHARED_SECRET=${KAPPLETS_SHAREDSECRET}
    networks:
      - net
  roboserver-service:
    build:
      context: .
      dockerfile: docker/roboserver/Dockerfile
    image: roboserver:${Version:-11.5.0.1.0.324}
    depends_on:
      - managementconsole-service
      - postgres-mcconfig-service
    networks:
      - net
    environment:
      - ROBOSERVER_ENABLE_MC_REGISTRATION=true
      - ROBOSERVER_MC_URL=http://managementconsole-service:8080/
      - ROBOSERVER_MC_CLUSTER=Non Production
      # change to use your own, match with the Management Console setting SERVICE_AUTHENTICATION_ROBOSERVER_SECRET
      - ROBOSERVER_MC_SHARED_SECRET=${ROBOSERVER_SHAREDSECRET}
      - ROBOSERVER_CONNECTION_TYPE=SocketConnectionType
      # - ROBOSERVER_SOCKET_SERVICE_PORT=50000
      - WRAPPER_MAX_MEMORY=2048
      - ROBOSERVER_SEC_ACCEPT_JDBC_DRIVERS=true
  postgres-robotlogs-service:
    image: postgres:10
    environment:
      - POSTGRES_USER=logdb
      - POSTGRES_PASSWORD=logdbpassword
      - POSTGRES_DB=logdb
    networks:
      - net
  postgres-robotdata:
    image: postgres:10
    environment:
      - POSTGRES_USER=robotdata
      - POSTGRES_PASSWORD=robotdatapassword
      - POSTGRES_DB=robotdata
    networks:
      - net
    ports:
      - 5434:5432
  kapplets-service:
    build:
      context: .
      dockerfile: docker/kapplets/Dockerfile
    image: kapplets:${Version:-11.5.0.1.0.324}
    depends_on:
      - managementconsole-service
      - postgres-kapplets-service
    networks:
      - net
    ports:
      - 8081:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-kapplets-service:5432/kapplets
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=kapplets
      - SPRING_DATASOURCE_PASSWORD=kapplets
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQL10Dialect
      - KAPPLETS_SERVICES_MC_CONNECTION_URL=http://managementconsole-service:8080/
      - spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
      - SLEEP_DELAY=30s
      - KAPPLETS_SERVICES_MC_CONNECTION_SERVICE_KAPPLETSBASEURL=
      - KAPPLETS_SERVICES_MC_CONNECTION_SERVICE_MCBASEURL=
      - KAPPLETS_SERVICES_MC_CONNECTION_SERVICE_SHAREDSECRET=${KAPPLETS_SHAREDSECRET}
